# Generated by Django 5.2.1 on 2025-05-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='tags',
            new_name='tag',
        ),
    ]
