# Generated by Django 5.2.1 on 2025-06-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0002_alter_game_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tag',
            field=models.ManyToManyField(blank=True, to='GameStore.tag'),
        ),
    ]
