# Generated by Django 5.2.1 on 2025-06-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='main_categories',
            field=models.ManyToManyField(blank=True, to='GameStore.maincategories'),
        ),
    ]
